#!/usr/bin/env bash
# Double the number of webservers
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html' > /dev/null 2>&1;
sudo mkdir -p /var/www/abdelrahman-ahmed.tech/html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/abdelrahman-ahmed.tech/html/custom_404.html > /dev/null 2>&1
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/abdulrahman-ahmed-202b02274/;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t\troot /var/www/abdelrahman-ahmed.tech/html;\n\t}' /etc/nginx/sites-available/default
sudo sed -i "/^server {/a \ \tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
sudo service nginx restart
