#!/usr/bin/env bash
# Install and configure HAproxy load palancer
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 440548-web-01 100.25.45.227:80
    server 440548-web-02 54.237.100.217:80
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null 2>&1
sudo service haproxy restart
